module.exports = {
  name: 'BJOU-APP',
  baseURL: `${cnApiServiceUrl}`,
  appId: 'bjouMobile',
  userTag: {
    username: 'username',
    usertoken: 'usertoken',
    userpower: 'userpower',
    userid: 'userid',
    useravatar: 'useravatar',
    userloginname: 'userloginname',
    portalToken: 'portalToken',
    portalUserId: 'portalUserId',
    orgCode: 'orgCode',
    portalUserName: 'portalUserName',
    doubleTake: 'doubleTake',
    portalHeadImg: 'portalHeadImg',
    portalHeadImgGK: 'portalHeadImgGK',
    bkStudentNumber: 'bkStudentNumber',
    userLoginId: 'userLoginId',
    oldAPP: false
  },
  api: {
    Login: '/login/cas',
    userLogout: '/logout',
    GetLessonDetails: '/course',
    RefreshLessonDetails: '/course/refresh',
    GetOpeningLessons: '/courselist/open',
    GetClosedLessons: '/courselist/due',
    GetBaseInfo: '/config',
    GetCurrentTask: '/task',
    GetAllTask: '/task/all',
    GetForum: '/forum',
    GetForumReply: '/forum/comments',
    AddNewForum: '/forum/add',
    ReplyForum: '/forum/postadd',
    UploadFiles: () => cnGetServiceUrl('moodle', '/webservice/upload.php'),
    GetPage: '/page',
    GetMoodleUserInfo: '/personal',
    GetMessageCount: '/msg/counts',
    GetMessage: '/msg/notices',
    GetTalkMessage: '/msg/messageList',
    ReadMessage: '/msg/markallread',
    ReadNotice: '/msg/readNotices',
    GetConversation: '/msg/messages',
    SendConversation: '/msg/sendmessages',
    GetQuiz: '/quiz',
    GetExamination: '/quiz/start',
    GetQuizReview: '/quiz/review',
    GetQuizSummary: '/quiz/summary',
    SendQuiz: '/quiz/process',
    GetLastTimeExamination: '/quiz/page',
    GetHomeworkInfo: '/assignment/getInformation',
    GetHomeWorkComments: '/assignment/getComments',
    GetMedalList: '/badge/user',
    GetGroupList: '/assignment/getTeamMembers',
    GetGradeList: '/grade',
    RefreshGrade: '/grade/refresh',
    getTeachersList: '/mentors',
    GetMember: '/group/users',
    GetContacts: '/personal/contacts',
    AddContacts: '/personal/addcontacts',
    DeleteContacts: '/personal/delcontacts',
    ADDHomeWork: '/assignment/add',
    UrlApi: 'url',
    GetFeedBack: '/questionnaire',
    GetFeedBackQuestions: '/questionnaire/getquestion',
    GetSuperClass: '/svp',
    GetResource: '/resource',
    GetFeedBackInfos: '/questionnaire/response',
    SendFeedBack: '/questionnaire/submit',
    CompleteFeedBack: '/questionnaire/unfinished',
    SetAvatar: '/personal/update',
    GetAttendance: '/attendance/course',
    GetAttendanceList: '/attendance/courseList',
    GetGradeCourseList: '/grade/courseList',
    AccessTime: '/log/accesstime',
    Log: '/log',
    UpdateInfo: '/personal/updateInfo',
    SendAssing: '/assignment/commit',
    GetSysNotice: 'notic/list',
    OpinionAdd: 'feedback/add',
    SeedOpinionFiles: () => cnGetServiceUrl('manager', '/file/upload'),
    MyOpinionList: '/feedback',
    ManualCompletion: '/cm/completion',
    GetVersion: '/config/appVersion',
    HelpUrl: (path) => cnGetServiceUrl('help', path),
    GetChoice: '/vote',
    SendChoice: '/vote/submit',
    GetFolder: '/folder/list',
    GetAppealList: '/feedback/findCourse',
    ReplyAppeal: '/feedback/replay',
    GetAppealCount: '/feedback/getReplyCount',
    GetAppealDetail: 'feedback/get',
    ReadAppeal: '/notic/readNotice',
    UploadRunningLogsApi: '/config/prints',
    GetMenusApi: '/config/module',
    sendMenusApi: '/config/saveModuleConfig',
    GetMoodleToken: '/config/getBkUser',
    GetLoginTips: '/login/info',
    GetPersonal: '/personal',
    UpdateCompleteStatus: '/resource/view',
    RefreshAttendance: '/attendance/refresh',
    UpdateUrlStatus: '/url/view',
    QueryStatus: '/course/cmState',

    // 门户登录
    Authentication: `${portalServiceUrl}/sso`,
    PortalLogin: `${portalServiceUrl}/login`,
    GetPortalToken: `${portalServiceUrl}/oauth/userToken`,
    SendPhoneLoginCode: `${portalSsoServiceUrl}/captcha/sms`,
    CheckFirstLogin: `${portalSsoServiceUrl}/current`,
    GetCaptchaImg: `${portalSsoServiceUrl}/captcha/img`,
    SsoPCLogin: `${portalSsoServiceUrl}/security_check`,
    SsogetPcPassword: `${portalSsoServiceUrl}/security/encode`,
    // 门户接口
    GetPaymentState: `${portalServiceUrl}/mobile/bkuser/getpaymentState`, // 缴费情况
    GetUserInfo: `${portalServiceUrl}/mobile/bkuser/get`, // 门户获取个人信息接口
    GetProgressList: `${portalServiceUrl}/mobile/bkcourse/academicSchedule`, // 学业进度表
    GetTimetable: `${portalServiceUrl}/mobile/bkcourse/list`, // 课程表
    GetApplyList: `${portalServiceUrl}/mobile/bkApplyInfo/list`, // 申请信息
    GetSchoolCalendar: `${portalServiceUrl}/mobile/information/schoolCalendar`, // 校历
    GetGraduationInfo: `${portalServiceUrl}/mobile/graduationInfo/list`, // 毕业信息
    GetCollectionList: `${portalServiceUrl}/mobile/informationCollection/list`, // 收藏
    GetNoticeList: `${portalServiceUrl}/mobile/information/list`, // 通知制度
    GetNoticeDetails: `${portalServiceUrl}/mobile/information/get`, // 通知制度详情
    GetInformationGK: `${portalServiceUrl}/mobile/information/informations`, // 国开教学日历
    GetStudentInfo: `${portalServiceUrl}/mobile/studentInfo/findStudentInfo`, // 国开学籍信息
    // GetExamGK: `${portalServiceUrl}/mobile/examscore/list`, // 旧版国开考试成绩
    GetExamGK: `${portalServiceUrl}/workbench/examscore/listKsdm`, // 2022.4新需求国开考试成绩
    GetCourseGK: `${portalServiceUrl}/mobile/courseInfo/listAll`, // 国开已选课程
    downFiles: `${portalServiceUrl}/mobile/information/stream/zip`, // 文档下载
    EnclosureDownload: `${portalServiceUrl}/file/downloadFile`, // 附件下载
    GetPortalUser: `${portalServiceUrl}/user/getUser`,
    GetCurrentUser: `${portalServiceUrl}/mobile/userInfo/getCurrentUser`,
    ChangCode: `${portalServiceUrl}/mobile/userInfo/changeCode`,
    Collection: `${portalServiceUrl}/mobile/informationCollection/update`,
    GetResetTypes: `${portalSsoServiceUrl}/cipherreset/getResetTypes`,
    SendCode: `${portalSsoServiceUrl}/cipherreset/sendCode`,
    PortalFileUpload: `${portalServiceUrl}/file/upload`, // 附件上传
    SetBKPortalAvatar: `${portalServiceUrl}/mobile/bkuser/updateImg`,
    SetGKPortalAvatar: `${portalServiceUrl}/mobile/userInfo/updateImg`,
    VerifyCode: `${portalSsoServiceUrl}/cipherreset/verifyCode`,
    UpdatePhoneOrEmail: `${portalSsoServiceUrl}/wx/portal/updatePhoneOrEmail`,
    ResetPassword: `${portalSsoServiceUrl}/cipherreset/resetPassword`,
    GetPasswordRule: `${portalSsoServiceUrl}/cipherreset/getPasswordRule`,
    ValidRule: `${portalSsoServiceUrl}/sso/validcharactersstrength`,
    SendCodeWithToken: `${portalSsoServiceUrl}/wx/portal/sendCode`,
    GetAccount: `${portalSsoServiceUrl}/cipherreset/getUserByAccountName`,
    FirstUpdatePassword: `${portalSsoServiceUrl}/user/updatePassword`,
    GetNoticeTabs: `${portalServiceUrl}/mobile/information/listCategory`,
    SetLastIdentity: `${portalSsoServiceUrl}/account/portalSelection`,
    GetLastIdentity: `${portalSsoServiceUrl}/account/portalSelectionSelect`,

    // 资源管理
    GetPlayInfo: `${portalResourceUrl}/content/foreign/playInfo`,
    AddPlayInfo: `${portalResourceUrl}/content/foreign/addLearnInfo`,
    UpdatePlayInfo: `${portalResourceUrl}/content/foreign/updateUserLearningFlow`,

    // 集成
    GetBjcb: 'https://www.bjcb.org.cn/oauths/token',
    Payment: 'https://bjkfdx.mp.sinojy.cn/api/user/loginByInterface',
    GetPaymentKey: 'http://192.168.0.204:8080/other/sso/jwgl',
  }
};
